version: '3'
services:
  app:
    build: .
    image: {{ cookiecutter.project_tag }}
    environment:
      SERVER_URL: ${SERVER_URL:-}
      SERVER_PROCS: ${SERVER_PROCS:-1}
    ports:
      - 8080:8080
