version: '3'
services:
  app:
    build: .
    image: {{ cookiecutter.project_tag }}
    environment:
      - DATABASE_URL
    ports:
      - 3000:3000

  db:
    build: db
    image: {{ cookiecutter.project_db_tag }}
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
